server:
  port: 8088
spring:
  application:
    name: proxy
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848

zuul:
  routes:
    user:
      path: /webapp/**
      serviceId: web-app
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000