zuul:
  routes:
    user:
      path: /webapp/**
      serviceId: web-app
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

management:
  endpoints:
    web:
      exposure:
        include: '*'