server:
  port: 8088
spring:
  application:
    name: proxy
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        id: web-app
        uri: lb://web-app
        predicates:
          path: /web-app/**
      routes:
        id: auth
        uri: lb://auth
        predicates:
          path: /auth/**
