server:
  port: 8088
spring:
  application:
    name: proxy
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

zuul:
  routes:
    web-app:
      path: /web-app/**
      serviceId: web-app
    auth:
      path: /auth/**
      serviceId: auth
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-per-route-connections: 20
