spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:userdb}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&autoReconnect=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      max-lifetime: 360000000