server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,auditevents,metrics,loggers,logfile,httptrace,flyway,liquidbase,shutdown,mappings,scheduledtasks,threaddump,heapdump,prometheus
