server:
  port: 8090
spring:
  application:
    name: user-svc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://132.232.59.17:3306/userdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    druid:
      db-type: mysql
  jpa:
    database: mysql
    show-sql: true
    jackson:
      time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

rocketmq:
  producer:
    groupName: ${spring.application.name}
    namesrvAddr: 114.67.106.146:9876
    default: false
  rocketmq:
    consumer:
      groupName: ${spring.application.name}
      namesrvAddr: 114.67.106.146:9876