spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:userdb}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    druid:
      db-type: mysql
  jpa:
    database: mysql
    show-sql: true
    jackson:
      time-zone: GMT+8

rocketmq:
  producer:
    groupName: ${spring.application.name}
    namesrvAddr:
    default: false
  rocketmq:
    consumer:
      groupName: ${spring.application.name}
      namesrvAddr:

management:
  endpoints:
    web:
      exposure:
        include: '*'