feign:
  sentinel:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

management:
  endpoints:
    promethus:
      enable: true
    web:
      exposure:
        include: '*'

kafka:
  host: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
