server:
  port: 8087
spring:
  application:
    name: web-app
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  sentinel:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000