DB_HOST: YOUR-DB-HOST
DB_USERNAME: YOUR-DB-USERNAME
DB_PASSWORD: YOUR-DB-PASSWORD

LOGGING_KAFKA_HOST: YOUR-KAFKA-HOST
LOGGING_KAFKA_PORT: YOUR-KAFKA-PORT

logging:
  config: classpath:logback-logstash.xml



